
name: bioemu
channels:
  - conda-forge
  - bioconda
  - pytorch
  - pyg
dependencies:
  - python=3.10
  - mdtraj>=1.9.9
  - pyg=2.6.1
  - pytorch=2.4.0
  - torchvision=0.19.0
  - modelcif=0.7
  - fire=0.7.0
  - huggingface_hub
  - hydra-core
  - dm-tree
  - stackprinter
  - typer

  # for Side-chain reconstruction and MD-relaxation
  - openmm=8.2.0
  - pdb2pqr=3.4.1

  # localcolabfold
  - git
  - pdbfixer

  - kalign2=2.04
  - hhsuite=3.3.0
  - mmseqs2=15.6f452
  - tensorflow
  - numpy=1.26.4

  - pip
  - pip:
    - bio>=1.5.9
    - jax[cuda12]==0.4.35